const val SVG_DEFAULT_FONT_SIZE = 12
const val SVG_HEXAGON_SIZE = 64
const val OUTPUT_PATH = "output"
const val CHAIN_TEXT_INDENT = 12
const val CHAIN_TEXT_LINE_START = "| %type "
const val DATA_TEXT_INDENT = 4

// Effects from Wonders
const val WHEAT_BOOST_TO_ADD_FROM_NEIGHBOR_WATER_SOURCE = 1.0
const val IRON_FORGE_BOOST_TO_ADD_FROM_NEIGHBOR_IRON_MINE = 1.0
const val STEEL_MILL_BOOST_TO_ADD_FROM_NEIGHBOR_EIFFEL_TOWER = 1.0
const val REFINERY_BOOST_TO_ADD_FROM_NEIGHBOR_OIL_SOURCE = 1.0