const BuildingSpecial = {
    HQ: "HQ",
    WorldWonder: "WorldWonder",
    NaturalWonder: "NaturalWonder"
}

const Buildings = {
    // #region Workers ////////////////////////////////////////////////////////////////////////////////////////
    Hut: {
        name: () => t(L.Hut),
        input: {},
        output: {Worker: 1},
        construction: {Wood: 1},
    },
    House: {
        name: () => t(L.House),
        input: {Wheat: 1, Water: 1},
        output: {Worker: 6},
        construction: {Wood: 1, Stone: 1, Water: 1},
    },
    Apartment: {
        name: () => t(L.Apartment),
        input: {Cheese: 1, Meat: 2, Bread: 1},
        output: {Worker: 84},
        construction: {Brick: 1, Cheese: 1, Meat: 1, Bread: 1},
    },
    Condo: {
        name: () => t(L.Condo),
        input: {Pizza: 3},
        output: {Worker: 510},
        construction: {Concrete: 3, Steel: 1},
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Resources //////////////////////////////////////////////////////////////////////////////////////
    WheatFarm: {
        name: () => t(L.WheatFarm),
        input: {},
        output: {Wheat: 1},
        construction: {Wood: 1},
    },
    StoneQuarry: {
        name: () => t(L.StoneQuarry),
        input: {},
        deposit: {Stone: true},
        output: {Stone: 1},
        construction: {Wood: 1},
    },
    LoggingCamp: {
        name: () => t(L.LoggingCamp),
        input: {},
        deposit: {Wood: true},
        output: {Wood: 1},
        construction: {Stone: 1},
    },
    Aqueduct: {
        name: () => t(L.Aqueduct),
        input: {},
        deposit: {Water: true},
        output: {Water: 1},
        construction: {Stone: 1},
    },
    IronMiningCamp: {
        name: () => t(L.IronMiningCamp),
        input: {},
        deposit: {Iron: true},
        output: {Iron: 1},
        construction: {Brick: 1},
    },
    CopperMiningCamp: {
        name: () => t(L.CopperMiningCamp),
        input: {},
        deposit: {Copper: true},
        output: {Copper: 1},
        construction: {Stone: 1, Wood: 1},
    },

    CoalMine: {
        name: () => t(L.CoalMine),
        input: {},
        deposit: {Coal: true},
        output: {Coal: 1},
        construction: {Iron: 1, Brick: 1, Lumber: 1},
    },

    Sandpit: {
        name: () => t(L.Sandpit),
        input: {},
        output: {Sand: 1},
        construction: {Wood: 1},
    },

    GoldMiningCamp: {
        name: () => t(L.GoldMiningCamp),
        input: {},
        deposit: {Gold: true},
        output: {Gold: 1},
        construction: {Brick: 1, Copper: 1},
    },

    UraniumMine: {
        name: () => t(L.UraniumMine),
        input: {},
        deposit: {Uranium: true},
        output: {Uranium: 1},
        construction: {Concrete: 1, Tool: 1},
    },

    UraniumEnrichmentPlant: {
        name: () => t(L.UraniumEnrichmentPlant),
        input: {Uranium: 10},
        output: {NuclearFuelRod: 1},
        construction: {Concrete: 4, Steel: 5},
        power: true,
    },

    OilWell: {
        name: () => t(L.OilWell),
        input: {},
        deposit: {Oil: true},
        output: {Oil: 1},
        construction: {Brick: 1, Tool: 1, Sand: 1},
    },

    NaturalGasWell: {
        name: () => t(L.NaturalGasWell),
        input: {},
        deposit: {NaturalGas: true},
        output: {NaturalGas: 1},
        construction: {Brick: 1, Tool: 1, Lumber: 1},
    },

    AluminumSmelter: {
        name: () => t(L.AluminumSmelter),
        input: {},
        deposit: {Aluminum: true},
        output: {Aluminum: 1},
        construction: {Tool: 1, Brick: 1, Lumber: 1},
    },

    CoalPowerPlant: {
        name: () => t(L.CoalPowerPlant),
        input: {Coal: 1},
        output: {Power: 1},
        construction: {Lumber: 5, Brick: 4},
    },

    GasPowerPlant: {
        name: () => t(L.GasPowerPlant),
        input: {NaturalGas: 2},
        output: {Power: 3},
        construction: {Concrete: 2},
    },

    HydroDam: {
        name: () => t(L.HydroDam),
        input: {},
        deposit: {Water: true},
        output: {Water: 1, Power: 2},
        construction: {Dynamite: 1, Concrete: 1},
    },

    NuclearPowerPlant: {
        name: () => t(L.NuclearPowerPlant),
        input: {NuclearFuelRod: 2},
        output: {Power: 65},
        construction: {Concrete: 16, Steel: 16},
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Military ///////////////////////////////////////////////////////////////////////////////////////
    SwordForge: {
        name: () => t(L.SwordForge),
        input: {Tool: 2},
        output: {Sword: 1},
        construction: {Tool: 1, Brick: 1, Copper: 2},
    },
    Armory: {
        name: () => t(L.Armory),
        input: {Tool: 2},
        output: {Armor: 1},
        construction: {Tool: 1, Brick: 1, Iron: 1, Wood: 1},
    },
    ChariotWorkshop: {
        name: () => t(L.ChariotWorkshop),
        input: {Horse: 2, Lumber: 2, Copper: 1},
        output: {Chariot: 1},
        construction: {Horse: 1, Copper: 1, Lumber: 2, Brick: 2},
    },
    KnightCamp: {
        name: () => t(L.KnightCamp),
        input: {Horse: 1, Armor: 1, Sword: 1},
        output: {Knight: 1},
    },
    CannonWorkshop: {
        name: () => t(L.CannonWorkshop),
        input: {Iron: 2, Wood: 1, Tool: 1},
        output: {Cannon: 1},
        construction: {Iron: 1, Wood: 1, Tool: 1, Brick: 1, Stone: 1},
    },
    GunpowderMill: {
        name: () => t(L.GunpowderMill),
        input: {Wood: 1, Coal: 1},
        output: {Gunpowder: 1},
        construction: {Stone: 1, Coal: 1},
    },
    DynamiteWorkshop: {
        name: () => t(L.DynamiteWorkshop),
        input: {Wheat: 1, Gunpowder: 1, Coal: 1},
        output: {Dynamite: 1},
        construction: {Stone: 2, Gunpowder: 1, Coal: 1},
    },
    SiegeWorkshop: {
        name: () => t(L.SiegeWorkshop),
        input: {Lumber: 2, Iron: 2, Tool: 1},
        output: {SiegeRam: 1},
        construction: {Lumber: 2, Iron: 1, Brick: 1, Tool: 1, Stone: 1},
    },
    CaravelBuilder: {
        name: () => t(L.CaravelBuilder),
        input: {Lumber: 5, Cloth: 2, Tool: 2},
        output: {Caravel: 1},
        construction: {Lumber: 5, Marble: 1, Brick: 2, Tool: 2},
    },
    GalleonBuilder: {
        name: () => t(L.GalleonBuilder),
        input: {Caravel: 1, Sword: 1, SiegeRam: 1, Armor: 1},
        output: {Galleon: 1},
    },
    FrigateBuilder: {
        name: () => t(L.FrigateBuilder),
        input: {Galleon: 1, Knight: 1, Cannon: 1, Lens: 1},
        output: {Frigate: 1},
    },
    RifleFactory: {
        name: () => t(L.RifleFactory),
        input: {Gunpowder: 5, Tool: 5},
        output: {Rifle: 1},
    },
    GatlingGunFactory: {
        name: () => t(L.GatlingGunFactory),
        input: {Rifle: 1, Gunpowder: 5},
        output: {GatlingGun: 1},
    },
    ArtilleryFactory: {
        name: () => t(L.ArtilleryFactory),
        input: {GatlingGun: 1, Dynamite: 1, Aluminum: 5},
        output: {Artillery: 1},
    },
    IroncladBuilder: {
        name: () => t(L.IroncladBuilder),
        input: {GatlingGun: 1, Rifle: 1, Frigate: 1},
        output: {Ironclad: 1},
    },
    BattleshipBuilder: {
        name: () => t(L.BattleshipBuilder),
        input: {Ironclad: 1, Artillery: 1, Cable: 5, Steel: 5, Aluminum: 5},
        output: {Battleship: 1},
        power: true,
    },
    TankFactory: {
        name: () => t(L.TankFactory),
        input: {Engine: 1, Steel: 10, Cannon: 1, GatlingGun: 1},
        output: {Tank: 1},
    },
    BiplaneFactory: {
        name: () => t(L.BiplaneFactory),
        input: {Engine: 1, Steel: 1, Lens: 1, Petrol: 5},
        output: {Biplane: 1},
    },
    RocketFactory: {
        name: () => t(L.RocketFactory),
        input: {Engine: 1, Artillery: 1, Steel: 5, Cable: 5, Petrol: 10},
        output: {Rocket: 1},
        power: true,
    },
    AtomicFacility: {
        name: () => t(L.AtomicFacility),
        input: {Dynamite: 10, Uranium: 10},
        output: {AtomicBomb: 1},
        power: true,
    },
    FighterJetPlant: {
        name: () => t(L.FighterJetPlant),
        input: {Airplane: 1, Artillery: 1},
        output: {FighterJet: 2},
        power: true,
    },
    AircraftCarrierYard: {
        name: () => t(L.AircraftCarrierYard),
        input: {Battleship: 1, FighterJet: 10},
        output: {AircraftCarrier: 1},
        power: true,
    },
    SubmarineYard: {
        name: () => t(L.SubmarineYard),
        input: {Ironclad: 2},
        output: {Submarine: 1},
        power: true,
    },
    NuclearSubmarineYard: {
        name: () => t(L.NuclearSubmarineYard),
        input: {Submarine: 2, NuclearMissile: 2},
        output: {NuclearSubmarine: 1},
        power: true,
    },
    NuclearMissileSilo: {
        name: () => t(L.NuclearMissileSilo),
        input: {AtomicBomb: 1, Rocket: 1},
        output: {NuclearMissile: 1},
        power: true,
    },
    Peacekeeper: {
        name: () => t(L.Peacekeeper),
        input: {NuclearMissile: 4, Diplomacy: 1, Radio: 1},
        output: {Peace: 1},
        power: true,
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Culture ////////////////////////////////////////////////////////////////////////////////////////
    WritersGuild: {
        name: () => t(L.WritersGuild),
        input: {Paper: 2},
        output: {Poem: 1},
        construction: {Brick: 2},
    },
    PoetrySchool: {
        name: () => t(L.PoetrySchool),
        input: {Paper: 2, Alcohol: 1},
        output: {Poem: 2},
        construction: {Brick: 1, Lumber: 1},
    },
    PaintersGuild: {
        name: () => t(L.PaintersGuild),
        input: {Paper: 2},
        output: {Painting: 1},
        construction: {Lumber: 1, Brick: 1},
    },
    MusiciansGuild: {
        name: () => t(L.MusiciansGuild),
        input: {Alcohol: 2},
        output: {Music: 1},
        construction: {Lumber: 2, Brick: 1},
    },
    ActorsGuild: {
        name: () => t(L.ActorsGuild),
        input: {Music: 1, Poem: 1},
        output: {Opera: 2},
    },
    Shrine: {
        name: () => t(L.Shrine),
        input: {Horse: 1, Alcohol: 1},
        output: {Faith: 1},
        construction: {Brick: 1, Lumber: 1, Alcohol: 1},
    },
    Church: {
        name: () => t(L.Church),
        input: {Music: 1, Poem: 1},
        output: {Faith: 3},
    },
    Mosque: {
        name: () => t(L.Mosque),
        input: {Cheese: 1, Opera: 1},
        output: {Faith: 4},
    },
    Pagoda: {
        name: () => t(L.Pagoda),
        input: {Painting: 1, Furniture: 1},
        output: {Faith: 3},
    },
    // Science is valued at 0.2
    Library: {
        name: () => t(L.Library),
        input: {Paper: 3},
        output: {Science: 105},
        construction: {Brick: 1},
    },
    School: {
        name: () => t(L.School),
        input: {Faith: 1, Poem: 1},
        output: {Science: 400},
    },
    University: {
        name: () => t(L.University),
        input: {Poem: 2, Faith: 2},
        output: {Philosophy: 1, Science: 250},
    },
    PublishingHouse: {
        name: () => t(L.PublishingHouse),
        input: {Philosophy: 2, Book: 10},
        output: {Newspaper: 1, Science: 1000},
    },
    MagazinePublisher: {
        name: () => t(L.MagazinePublisher),
        input: {Sports: 2, Book: 10},
        output: {Magazine: 1, Science: 1000},
    },
    ResearchLab: {
        name: () => t(L.ResearchLab),
        input: {Culture: 2, Philosophy: 2},
        output: {Science: 5000},
    },
    ResearchFund: {
        name: () => t(L.ResearchFund),
        input: {Banknote: 1, Bond: 1},
        output: {Science: 25940},
    },
    ComputerLab: {
        name: () => t(L.ComputerLab),
        input: {Computer: 1},
        output: {Science: 79930},
        power: true,
    },
    Museum: {
        name: () => t(L.Museum),
        input: {Music: 2, Painting: 2},
        output: {Culture: 1},
    },
    Courthouse: {
        name: () => t(L.Courthouse),
        input: {Philosophy: 1, Faith: 1, Culture: 1},
        output: {Law: 1},
    },
    Stadium: {
        name: () => t(L.Stadium),
        input: {Culture: 1, Opera: 1, Philosophy: 1},
        output: {Sports: 1},
    },
    Parliament: {
        name: () => t(L.Parliament),
        input: {Culture: 2, Philosophy: 2, Law: 2},
        output: {Politics: 1},
    },
    MovieStudio: {
        name: () => t(L.MovieStudio),
        input: {Sports: 5, Lens: 5, Garment: 5},
        output: {Movie: 1},
        power: true,
    },
    RadioStation: {
        name: () => t(L.RadioStation),
        input: {Magazine: 5, Newspaper: 5, Culture: 5},
        output: {Radio: 1},
        power: true,
    },
    Embassy: {
        name: () => t(L.Embassy),
        input: {Law: 5, Politics: 5, Philosophy: 5},
        output: {Diplomacy: 1},
    },
    TVStation: {
        name: () => t(L.TVStation),
        input: {Radio: 2, Movie: 10},
        output: {TV: 1},
        power: true,
    },
    InternetServiceProvider: {
        name: () => t(L.InternetServiceProvider),
        input: {Computer: 1, OpticalFiber: 5},
        output: {Internet: 1},
        power: true,
    },
    SoftwareCompany: {
        name: () => t(L.SoftwareCompany),
        input: {Computer: 1, Philosophy: 10},
        output: {Software: 1},
        power: true,
    },
    SupercomputerLab: {
        name: () => t(L.SupercomputerLab),
        input: {Software: 1, Computer: 5},
        output: {Supercomputer: 1},
        power: true,
    },
    CivGPT: {
        name: () => t(L.CivGPT),
        input: {Internet: 1, Supercomputer: 2, Radio: 1},
        output: {CivGPT: 1},
        power: true,
    },
    CivTok: {
        name: () => t(L.CivTok),
        input: {Internet: 1, Politics: 1},
        output: {CivTok: 1},
        power: true,
    },
    CivOasis: {
        name: () => t(L.CivOasis),
        input: {CivTok: 1, Supercomputer: 1, Diplomacy: 2},
        output: {CivOasis: 1},
        power: true,
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Food & Light Industry //////////////////////////////////////////////////////////////////////////
    CottonPlantation: {
        name: () => t(L.CottonPlantation),
        input: {},
        output: {Cotton: 1},
        construction: {Wood: 1},
    },
    CottonMill: {
        name: () => t(L.CottonMill),
        input: {Cotton: 2},
        output: {Cloth: 1},
        construction: {Brick: 1, Lumber: 1},
    },
    GarmentWorkshop: {
        name: () => t(L.GarmentWorkshop),
        input: {Cloth: 2},
        output: {Garment: 1},
    },
    FurnitureWorkshop: {
        name: () => t(L.FurnitureWorkshop),
        input: {Lumber: 2, Copper: 1},
        output: {Furniture: 1},
    },
    PrintingHouse: {
        name: () => t(L.PrintingHouse),
        input: {Paper: 5, Poem: 1},
        output: {Book: 1},
    },
    FlourMill: {
        name: () => t(L.FlourMill),
        input: {Wheat: 2},
        output: {Flour: 1},
        construction: {Brick: 1},
    },
    LivestockFarm: {
        name: () => t(L.LivestockFarm),
        input: {Wheat: 2},
        output: {Meat: 1, Milk: 1},
        construction: {Lumber: 1},
    },
    PoultryFarm: {
        name: () => t(L.PoultryFarm),
        input: {Wheat: 2},
        output: {Meat: 2},
        construction: {Lumber: 1},
    },
    DairyFarm: {
        name: () => t(L.DairyFarm),
        input: {Wheat: 2},
        output: {Milk: 2},
        construction: {Brick: 1},
    },
    // LivestockFarm: {
    //    name: () => t(L.LivestockFarm),
    //    input: { Wheat: 2 },
    //    output: { Meat: 1, Milk: 1 },
    //    construction: { Lumber: 1 },
    // },
    Stable: {
        name: () => t(L.Stable),
        input: {Wheat: 2},
        output: {Horse: 1},
        construction: {Lumber: 1},
    },
    Bakery: {
        name: () => t(L.Bakery),
        input: {Water: 1, Flour: 1},
        output: {Bread: 1},
        construction: {Brick: 1, Lumber: 1, Stone: 1},
    },
    CheeseMaker: {
        name: () => t(L.CheeseMaker),
        input: {Milk: 2},
        output: {Cheese: 1},
        construction: {Brick: 1, Lumber: 1},
    },
    Brewery: {
        name: () => t(L.Brewery),
        input: {Wheat: 1, Water: 1},
        output: {Alcohol: 1},
        construction: {Copper: 1},
    },
    PaperMaker: {
        name: () => t(L.PaperMaker),
        input: {Wood: 1, Water: 1},
        output: {Paper: 1},
        construction: {Wood: 1, Stone: 1},
    },
    Pizzeria: {
        name: () => t(L.Pizzeria),
        input: {Cheese: 1, Meat: 1, Flour: 2, Water: 2},
        output: {Pizza: 1},
    },
    PlasticsFactory: {
        name: () => t(L.PlasticsFactory),
        input: {Oil: 2},
        output: {Plastics: 1},
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Heavy Industry /////////////////////////////////////////////////////////////////////////////////
    LumberMill: {
        name: () => t(L.LumberMill),
        input: {Wood: 2},
        output: {Lumber: 1},
        construction: {Stone: 2},
    },
    Glassworks: {
        name: () => t(L.Glassworks),
        input: {Sand: 2},
        output: {Glass: 1},
        construction: {Brick: 1, Wood: 2},
    },
    LensWorkshop: {
        name: () => t(L.LensWorkshop),
        input: {Glass: 2},
        output: {Lens: 1},
    },
    Blacksmith: {
        name: () => t(L.Blacksmith),
        input: {Copper: 1, Wood: 1},
        output: {Tool: 1},
        construction: {Brick: 1},
    },
    IronForge: {
        name: () => t(L.IronForge),
        input: {Iron: 1},
        output: {Tool: 1},
        construction: {Brick: 1},
    },
    Brickworks: {
        name: () => t(L.Brickworks),
        input: {Stone: 2},
        output: {Brick: 1},
        construction: {Wood: 2},
    },
    Marbleworks: {
        name: () => t(L.Marbleworks),
        input: {Stone: 2, Tool: 1},
        output: {Marble: 1},
    },
    ConcretePlant: {
        name: () => t(L.ConcretePlant),
        input: {Brick: 1, Sand: 2, Tool: 1},
        output: {Concrete: 1},
    },
    SteelMill: {
        name: () => t(L.SteelMill),
        input: {Iron: 1, Coal: 1},
        output: {Steel: 1},
        construction: {Brick: 1, Coal: 1},
    },
    SiliconSmelter: {
        name: () => t(L.SiliconSmelter),
        input: {Sand: 5},
        output: {Silicon: 1},
        construction: {Brick: 1, Coal: 1},
        power: true,
    },
    CableFactory: {
        name: () => t(L.CableFactory),
        input: {Copper: 5},
        output: {Cable: 1},
    },
    Steamworks: {
        name: () => t(L.Steamworks),
        input: {Iron: 1, Coal: 1, Tool: 1},
        output: {Engine: 1},
    },
    LocomotiveFactory: {
        name: () => t(L.LocomotiveFactory),
        input: {Engine: 1, Steel: 10},
        output: {Train: 1},
    },
    MaglevFactory: {
        name: () => t(L.MaglevFactory),
        input: {Train: 15, Airplane: 15, Car: 15},
        output: {Maglev: 1},
        power: true,
    },
    CarFactory: {
        name: () => t(L.CarFactory),
        input: {Engine: 1, Steel: 1, Furniture: 1, Cable: 1, Plastics: 1, Petrol: 5},
        output: {Car: 1},
        power: true,
    },
    RobocarFactory: {
        name: () => t(L.RobocarFactory),
        input: {Car: 5, Supercomputer: 2, Satellite: 1},
        output: {Robocar: 1},
        power: true,
    },
    SpaceCenter: {
        name: () => t(L.SpaceCenter),
        input: {Maglev: 1, Radio: 1, Supercomputer: 1},
        output: {PlanetaryRover: 2},
        power: true,
    },
    OilRefinery: {
        name: () => t(L.OilRefinery),
        input: {Oil: 2},
        output: {Petrol: 1},
        construction: {Steel: 1},
    },
    SatelliteFactory: {
        name: () => t(L.SatelliteFactory),
        input: {Rocket: 2},
        output: {Satellite: 1},
        power: true,
    },
    AirplaneFactory: {
        name: () => t(L.AirplaneFactory),
        input: {Biplane: 2},
        output: {Airplane: 1},
        power: true,
    },
    SpacecraftFactory: {
        name: () => t(L.SpacecraftFactory),
        input: {Rocket: 2, Satellite: 2, Airplane: 2},
        output: {Spacecraft: 1},
        power: true,
    },
    SemiconductorFab: {
        name: () => t(L.SemiconductorFab),
        input: {Silicon: 10, Copper: 10},
        output: {Semiconductor: 1},
        power: true,
    },
    ComputerFactory: {
        name: () => t(L.ComputerFactory),
        input: {Semiconductor: 5, Plastics: 5, Aluminum: 5},
        output: {Computer: 1},
        power: true,
    },
    OpticalFiberPlant: {
        name: () => t(L.OpticalFiberPlant),
        input: {Cable: 10, Glass: 10, Plastics: 10},
        output: {OpticalFiber: 1},
        power: true,
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Financial & Trade //////////////////////////////////////////////////////////////////////////////
    CoinMint: {
        name: () => t(L.CoinMint),
        input: {Gold: 3},
        output: {Coin: 1},
        construction: {Gold: 2, Lumber: 1, Copper: 1},
    },
    Bank: {
        name: () => t(L.Bank),
        input: {Coin: 3},
        output: {Banknote: 1},
    },
    BondMarket: {
        name: () => t(L.BondMarket),
        input: {Banknote: 3},
        output: {Bond: 1},
    },
    StockExchange: {
        name: () => t(L.StockExchange),
        input: {Bond: 3},
        output: {Stock: 1},
    },
    ForexMarket: {
        name: () => t(L.ForexMarket),
        input: {Banknote: 2, Bond: 2},
        output: {Forex: 1},
    },
    MutualFund: {
        name: () => t(L.MutualFund),
        input: {Forex: 1, Stock: 1},
        output: {MutualFund: 1},
    },
    HedgeFund: {
        name: () => t(L.HedgeFund),
        input: {MutualFund: 2},
        output: {HedgeFund: 1},
    },
    BitcoinMiner: {
        name: () => t(L.BitcoinMiner),
        input: {HedgeFund: 2, CivTok: 1},
        output: {Bitcoin: 1},
        power: true,
    },
    Caravansary: {
        name: () => t(L.Caravansary),
        desc: () => t(L.CaravansaryDesc),
        input: {},
        output: {},
        construction: {Brick: 1, Horse: 1, Tool: 1},
    },
    Market: {
        name: () => t(L.Market),
        input: {},
        output: {},
        desc: () => t(L.MarketDesc),
        construction: {Brick: 2, Copper: 2, Lumber: 2},
    },
    Warehouse: {
        name: () => t(L.Warehouse),
        input: {},
        output: {},
        desc: () => t(L.WarehouseDesc),
        construction: {Lumber: 1, Brick: 1, Horse: 1},
    },
    CloneFactory: {
        name: () => t(L.CloneFactory),
        input: {},
        output: {},
        desc: () => t(L.CloneFactoryDesc),
        construction: {Software: 5, Tank: 5},
        power: true,
    },
    CloneLab: {
        name: () => t(L.CloneLab),
        input: {},
        output: {},
        desc: () => t(L.CloneLabDesc),
        construction: {Rocket: 5, Computer: 5},
        power: true,
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region Functional Wonders /////////////////////////////////////////////////////////////////////////////
    Headquarter: {
        name: () => t(L.Headquarter),
        input: {},
        output: {Worker: 10},
        vision: 3,
        max: 0,
        special: BuildingSpecial.HQ,
    },
    Statistics: {
        name: () => t(L.StatisticsOffice),
        desc: () => t(L.StatisticsOfficeDesc),
        input: {},
        output: {},
        construction: {Brick: 100, Wood: 100, Lumber: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
    },
    Petra: {
        name: () => t(L.Petra),
        desc: () => t(L.PetraDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Gold: 500},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Petra",
    },
    // #endregion

    // #region Natural Wonders ////////////////////////////////////////////////////////////////////////////////
    Alps: {
        name: () => t(L.Alps),
        desc: () => t(L.AlpsDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Alps",
        special: BuildingSpecial.NaturalWonder,
    },
    GrottaAzzurra: {
        name: () => t(L.GrottaAzzurra),
        desc: () => t(L.GrottaAzzurraDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Blue_Grotto_(Capri)",
        special: BuildingSpecial.NaturalWonder,
    },
    Aphrodite: {
        name: () => t(L.Aphrodite),
        desc: () => t(L.AphroditeDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Aphrodite",
        special: BuildingSpecial.NaturalWonder,
    },
    Poseidon: {
        name: () => t(L.Poseidon),
        desc: () => t(L.PoseidonDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Poseidon",
        special: BuildingSpecial.NaturalWonder,
    },
    NileRiver: {
        name: () => t(L.NileRiver),
        desc: () => t(L.NileRiverDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Nile",
        special: BuildingSpecial.NaturalWonder,
    },
    MountSinai: {
        name: () => t(L.MountSinai),
        desc: () => t(L.MountSinaiDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Mount_Sinai",
        special: BuildingSpecial.NaturalWonder,
    },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // #region World Wonders //////////////////////////////////////////////////////////////////////////////////
    Stonehenge: {
        name: () => t(L.Stonehenge),
        desc: () => t(L.StonehengeDesc),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Stonehenge",
        construction: {Stone: 300},
    },
    HatshepsutTemple: {
        name: () => t(L.HatshepsutTemple),
        desc: () => t(L.HatshepsutTempleDesc),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Mortuary_Temple_of_Hatshepsut",
        construction: {Stone: 100, Wood: 100, Copper: 100},
    },
    LighthouseOfAlexandria: {
        name: () => t(L.LighthouseOfAlexandria),
        desc: () => t(L.LighthouseOfAlexandriaDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Iron: 100, Marble: 100, Tool: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Lighthouse_of_Alexandria",
    },
    PyramidOfGiza: {
        name: () => t(L.PyramidOfGiza),
        desc: () => t(L.PyramidOfGizaDesc),
        input: {},
        output: {},
        construction: {Stone: 300},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Great_Pyramid_of_Giza",
    },
    ColossusOfRhodes: {
        name: () => t(L.ColossusOfRhodes),
        desc: () => t(L.ColossusOfRhodesDesc),
        input: {},
        output: {},
        construction: {Stone: 300},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Colossus_of_Rhodes",
    },
    GreatMosqueOfSamarra: {
        name: () => t(L.GreatMosqueOfSamarra),
        desc: () => t(L.GreatMosqueOfSamarraDescV2),
        input: {},
        output: {},
        construction: {Sand: 100, Brick: 100, Cotton: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Great_Mosque_of_Samarra",
    },
    HangingGarden: {
        name: () => t(L.HangingGarden),
        desc: () => t(L.HangingGardenDesc),
        input: {},
        output: {},
        construction: {Stone: 100, Water: 100, Copper: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Hanging_Gardens_of_Babylon",
    },
    TempleOfHeaven: {
        name: () => t(L.TempleOfHeaven),
        desc: () => t(L.TempleOfHeavenDesc),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        construction: {Iron: 100, Bread: 100, Cheese: 100},
        wikipedia: "Temple_of_Heaven",
    },
    Parthenon: {
        name: () => t(L.Parthenon),
        desc: () => t(L.ParthenonDescV2),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        construction: {Marble: 100, Painting: 100, Music: 100},
        wikipedia: "Parthenon",
    },
    TempleOfArtemis: {
        name: () => t(L.TempleOfArtemis),
        desc: () => t(L.TempleOfArtemisDesc),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        construction: {Armor: 100, Sword: 100, Marble: 100},
        wikipedia: "Temple_of_Artemis",
    },
    LuxorTemple: {
        name: () => t(L.LuxorTemple),
        desc: () => t(L.LuxorTempleDescV2),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        construction: {Tool: 100, Cloth: 100, Furniture: 100},
        wikipedia: "Luxor_Temple",
    },
    ChichenItza: {
        name: () => t(L.ChichenItza),
        desc: () => t(L.ChichenItzaDesc),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        construction: {Stone: 100, Armor: 100, SiegeRam: 100},
        wikipedia: "Chichen_Itza",
    },
    MausoleumAtHalicarnassus: {
        name: () => t(L.MausoleumAtHalicarnassus),
        desc: () => t(L.MausoleumAtHalicarnassusDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Marble: 100, Lumber: 100, Tool: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Mausoleum_at_Halicarnassus",
    },
    HagiaSophia: {
        name: () => t(L.HagiaSophia),
        desc: () => t(L.HagiaSophiaDescV2),
        input: {},
        construction: {Faith: 150, Marble: 150, Knight: 150},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Hagia_Sophia",
    },
    AngkorWat: {
        name: () => t(L.AngkorWat),
        desc: () => t(L.AngkorWatDesc),
        input: {},
        output: {},
        construction: {Faith: 100, Tool: 100, Marble: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Angkor_Wat",
    },
    TerracottaArmy: {
        name: () => t(L.TerracottaArmy),
        desc: () => t(L.TerracottaArmyDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Chariot: 100, Iron: 100, Stone: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Terracotta_Army",
    },
    Persepolis: {
        name: () => t(L.Persepolis),
        desc: () => t(L.PersepolisDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Stone: 100, Wood: 100, Copper: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Persepolis",
    },
    OxfordUniversity: {
        name: () => t(L.OxfordUniversity),
        desc: () => t(L.OxfordUniversityDescV3),
        input: {},
        output: {},
        max: 1,
        construction: {Faith: 100, Philosophy: 100, Poem: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "University_of_Oxford",
    },
    SaintBasilsCathedral: {
        name: () => t(L.SaintBasilsCathedral),
        desc: () => t(L.SaintBasilsCathedralDescV2),
        input: {},
        output: {},
        max: 1,
        construction: {Furniture: 100, Gunpowder: 100, Lens: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Saint_Basil%27s_Cathedral",
    },
    ForbiddenCity: {
        name: () => t(L.ForbiddenCity),
        desc: () => t(L.ForbiddenCityDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Banknote: 100, Marble: 100, Book: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Forbidden_City",
    },
    HimejiCastle: {
        name: () => t(L.HimejiCastle),
        desc: () => t(L.HimejiCastleDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Caravel: 100, Galleon: 100, Frigate: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Himeji_Castle",
    },
    TajMahal: {
        name: () => t(L.TajMahal),
        desc: () => t(L.TajMahalDescV2),
        input: {},
        output: {},
        construction: {Faith: 100, Marble: 100, Garment: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Taj_Mahal",
    },
    Colosseum: {
        name: () => t(L.Colosseum),
        desc: () => t(L.ColosseumDesc),
        input: {Chariot: 10},
        output: {},
        construction: {Brick: 100, Chariot: 100, Alcohol: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Colosseum",
    },
    MogaoCaves: {
        name: () => t(L.MogaoCaves),
        desc: () => t(L.MogaoCavesDescV3),
        input: {},
        output: {},
        construction: {Faith: 100, Marble: 100, Painting: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Mogao_Caves",
    },
    StatueOfZeus: {
        name: () => t(L.StatueOfZeus),
        desc: () => t(L.StatueOfZeusDesc),
        input: {},
        output: {},
        construction: {Marble: 100, Brick: 100, Music: 100},
        max: 1,
        wikipedia: "Statue_of_Zeus_at_Olympia",
        special: BuildingSpecial.WorldWonder,
    },
    CircusMaximus: {
        name: () => t(L.CircusMaximus),
        desc: () => t(L.CircusMaximusDescV2),
        input: {},
        output: {},
        construction: {Music: 100, Poem: 100, Painting: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Circus_Maximus",
    },
    EiffelTower: {
        name: () => t(L.EiffelTower),
        desc: () => t(L.EiffelTowerDesc),
        input: {},
        output: {},
        construction: {Steel: 300},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Eiffel_Tower",
    },
    Rijksmuseum: {
        name: () => t(L.Rijksmuseum),
        desc: () => t(L.RijksmuseumDesc),
        input: {},
        output: {},
        construction: {Newspaper: 100, Culture: 100, Concrete: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Rijksmuseum",
    },
    SummerPalace: {
        name: () => t(L.SummerPalace),
        desc: () => t(L.SummerPalaceDesc),
        input: {},
        output: {},
        construction: {Gunpowder: 100, Rifle: 100, GatlingGun: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Summer_Palace",
    },
    StatueOfLiberty: {
        name: () => t(L.StatueOfLiberty),
        desc: () => t(L.StatueOfLibertyDesc),
        input: {},
        output: {},
        construction: {Philosophy: 100, Politics: 100, Law: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Statue_of_Liberty",
    },
    Neuschwanstein: {
        name: () => t(L.Neuschwanstein),
        desc: () => t(L.NeuschwansteinDesc),
        input: {},
        output: {},
        construction: {Rifle: 100, Bond: 100, Cannon: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Neuschwanstein_Castle",
    },
    BrandenburgGate: {
        name: () => t(L.BrandenburgGate),
        desc: () => t(L.BrandenburgGateDesc),
        input: {},
        output: {},
        construction: {Train: 100, Politics: 100, Concrete: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Brandenburg_Gate",
    },
    GrandBazaar: {
        name: () => t(L.GrandBazaar),
        desc: () => t(L.GrandBazaarDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Coin: 100, Garment: 100, Furniture: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Grand_Bazaar,_Istanbul",
    },
    AbuSimbel: {
        name: () => t(L.AbuSimbel),
        desc: () => t(L.AbuSimbelDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Stone: 100, Brick: 100, Lumber: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Abu_Simbel",
    },
    GreatSphinx: {
        name: () => t(L.GreatSphinx),
        desc: () => t(L.GreatSphinxDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Stone: 100, Brick: 100, Lumber: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Great_Sphinx_of_Giza",
    },
    Hollywood: {
        name: () => t(L.Hollywood),
        desc: () => t(L.HollywoodDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Magazine: 100, Movie: 100, Newspaper: 100},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Hollywood,_Los_Angeles",
    },
    GoldenGateBridge: {
        name: () => t(L.GoldenGateBridge),
        desc: () => t(L.GoldenGateBridgeDesc),
        input: {},
        output: {},
        construction: {Steel: 100, Movie: 100, Radio: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Golden_Gate_Bridge",
    },
    CristoRedentor: {
        name: () => t(L.CristoRedentor),
        desc: () => t(L.CristoRedentorDesc),
        input: {},
        output: {},
        construction: {Concrete: 100, Sports: 100, Politics: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Christ_the_Redeemer_(statue)",
    },
    UnitedNations: {
        name: () => t(L.UnitedNations),
        desc: () => t(L.UnitedNationsDesc),
        input: {},
        output: {},
        construction: {Politics: 100, Law: 100, Diplomacy: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "United_Nations",
    },
    ManhattanProject: {
        name: () => t(L.ManhattanProject),
        desc: () => t(L.ManhattanProjectDesc),
        input: {},
        output: {},
        construction: {NuclearFuelRod: 500},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Manhattan_Project",
    },
    SagradaFamilia: {
        name: () => t(L.SagradaFamilia),
        desc: () => t(L.SagradaFamiliaDesc),
        input: {},
        output: {},
        construction: {Tank: 100, Biplane: 100, Train: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Sagrada_Família",
    },
    GreatWall: {
        name: () => t(L.GreatWall),
        desc: () => t(L.GreatWallDesc),
        input: {},
        output: {},
        construction: {Brick: 100, Tool: 100, Horse: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Great_Wall_of_China",
    },
    YellowCraneTower: {
        name: () => t(L.YellowCraneTower),
        desc: () => t(L.YellowCraneTowerDesc),
        input: {},
        output: {},
        construction: {Furniture: 100, Sword: 100, Coin: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Yellow_Crane_Tower",
    },
    PorcelainTower: {
        name: () => t(L.PorcelainTower),
        desc: () => t(L.PorcelainTowerDesc),
        input: {},
        output: {},
        construction: {Banknote: 100, Garment: 100, Knight: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Porcelain_Tower_of_Nanjing",
    },
    MountTai: {
        name: () => t(L.MountTai),
        desc: () => t(L.MountTaiDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        special: BuildingSpecial.NaturalWonder,
        wikipedia: "Mount_Tai",
    },
    YangtzeRiver: {
        name: () => t(L.YangtzeRiver),
        desc: () => t(L.YangtzeRiverDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        special: BuildingSpecial.NaturalWonder,
        wikipedia: "Yangtze",
    },
    // SydneyOperaHouse: {
    //    name: () => t(L.SydneyOperaHouse),
    //    desc: () => t(L.SydneyOperaHouseDescV2),
    //    input: {},
    //    output: {},
    //    construction: { Forex: 300 },
    //    max: 1,
    //    special: BuildingSpecial.WorldWonder,
    //    wikipedia: "Sydney_Opera_House",
    // },
    CNTower: {
        name: () => t(L.CNTower),
        desc: () => t(L.CNTowerDesc),
        input: {},
        output: {},
        construction: {Movie: 100, Radio: 100, Diplomacy: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "CN_Tower",
    },
    // GatewayArch: {
    //    name: () => t(L.GatewayArch),
    //    desc: () => t(L.GatewayArchDesc),
    //    input: {},
    //    output: {},
    //    construction: { Forex: 300 },
    //    max: 1,
    //    special: BuildingSpecial.WorldWonder,
    //    wikipedia: "Gateway_Arch",
    // },
    SpaceNeedle: {
        name: () => t(L.SpaceNeedle),
        desc: () => t(L.SpaceNeedleDesc),
        input: {},
        output: {},
        construction: {Battleship: 150, Rocket: 150, Car: 150},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Space_Needle",
    },
    ApolloProgram: {
        name: () => t(L.ApolloProgram),
        desc: () => t(L.ApolloProgramDesc),
        input: {},
        output: {},
        construction: {FighterJet: 100, Satellite: 100, Spacecraft: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Apollo_program",
    },
    Atomium: {
        name: () => t(L.Atomium),
        desc: () => t(L.AtomiumDescV2),
        input: {},
        output: {},
        construction: {NuclearFuelRod: 100, AtomicBomb: 100, Artillery: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Atomium",
    },
    ChoghaZanbil: {
        name: () => t(L.ChoghaZanbil),
        desc: () => t(L.ChoghaZanbilDescV2),
        input: {},
        output: {},
        construction: {Water: 100, Wood: 100, Stone: 100, Wheat: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Chogha_Zanbil",
    },
    Broadway: {
        name: () => t(L.Broadway),
        desc: () => t(L.BroadwayDesc),
        input: {},
        output: {},
        construction: {Opera: 100, Culture: 100, Bond: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Broadway_theatre",
    },
    TheMet: {
        name: () => t(L.TheMet),
        desc: () => t(L.TheMetDesc),
        input: {},
        output: {},
        construction: {Book: 100, Law: 100, Rifle: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Metropolitan_Museum_of_Art",
    },
    WallStreet: {
        name: () => t(L.WallStreet),
        desc: () => t(L.WallStreetDesc),
        input: {},
        output: {},
        construction: {Bond: 100, Law: 100, Banknote: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Wall_Street",
    },

    Shenandoah: {
        name: () => t(L.Shenandoah),
        desc: () => t(L.ShenandoahDescV2),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Shenandoah_Valley",
        special: BuildingSpecial.NaturalWonder,
    },

    NiagaraFalls: {
        name: () => t(L.NiagaraFalls),
        desc: () => t(L.NiagaraFallsDescV2),
        input: {},
        output: {},
        construction: {},
        max: 0,
        wikipedia: "Niagara_Falls",
        special: BuildingSpecial.NaturalWonder,
    },

    StPetersBasilica: {
        name: () => t(L.StPetersBasilica),
        desc: () => t(L.StPetersBasilicaDescV2),
        input: {},
        output: {},
        max: 1,
        construction: {Faith: 300},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "St._Peter%27s_Basilica",
    },

    ProphetsMosque: {
        name: () => t(L.ProphetsMosque),
        desc: () => t(L.ProphetsMosqueDesc),
        input: {},
        output: {},
        max: 1,
        construction: {Faith: 300},
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Prophet%27s_Mosque",
    },

    GreatDagonPagoda: {
        name: () => t(L.GreatDagonPagoda),
        desc: () => t(L.GreatDagonPagodaDescV2),
        input: {},
        output: {},
        construction: {Faith: 300},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Shwedagon_Pagoda",
    },

    Pantheon: {
        name: () => t(L.Pantheon),
        desc: () => t(L.PantheonDescV2),
        input: {},
        output: {},
        construction: {Faith: 300},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Pantheon,_Rome",
    },

    WallOfBabylon: {
        name: () => t(L.WallOfBabylon),
        desc: () => t(L.WallOfBabylonDesc),
        input: {},
        output: {},
        construction: {Brick: 100, Lumber: 100, Sand: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Ishtar_Gate",
    },

    TowerOfBabel: {
        name: () => t(L.TowerOfBabel),
        desc: () => t(L.TowerOfBabelDesc),
        input: {},
        output: {},
        construction: {Brick: 100, Lumber: 100, Sand: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Tower_of_Babel",
    },

    ZigguratOfUr: {
        name: () => t(L.ZigguratOfUr),
        desc: () => t(L.ZigguratOfUrDesc),
        input: {},
        output: {},
        construction: {Brick: 100, Lumber: 100, Sand: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Ziggurat_of_Ur",
    },

    EuphratesRiver: {
        name: () => t(L.EuphratesRiver),
        desc: () => t(L.EuphratesRiverDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        special: BuildingSpecial.NaturalWonder,
        wikipedia: "Euphrates",
    },

    ZagrosMountains: {
        name: () => t(L.ZagrosMountains),
        desc: () => t(L.ZagrosMountainsDesc),
        input: {},
        output: {},
        construction: {},
        max: 0,
        special: BuildingSpecial.NaturalWonder,
        wikipedia: "Zagros_Mountains",
    },

    InternationalSpaceStation: {
        name: () => t(L.InternationalSpaceStation),
        desc: () => t(L.InternationalSpaceStationDesc),
        input: {},
        output: {},
        construction: {Spacecraft: 100, AircraftCarrier: 100, NuclearSubmarine: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "International_Space_Station",
    },

    MarinaBaySands: {
        name: () => t(L.MarinaBaySands),
        desc: () => t(L.MarinaBaySandsDesc),
        input: {},
        output: {},
        construction: {TV: 100, CivTok: 100, MutualFund: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Marina_Bay_Sands",
    },

    PalmJumeirah: {
        name: () => t(L.PalmJumeirah),
        desc: () => t(L.PalmJumeirahDesc),
        input: {},
        output: {},
        construction: {HedgeFund: 100, Bitcoin: 100, Supercomputer: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Palm_Jumeirah",
    },

    AldersonDisk: {
        name: () => t(L.AldersonDisk),
        desc: () => t(L.AldersonDiskDesc),
        input: {},
        output: {},
        construction: {CivOasis: 100, Robocar: 100, Bitcoin: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Alderson_disk",
    },

    DysonSphere: {
        name: () => t(L.DysonSphere),
        desc: () => t(L.DysonSphereDesc),
        input: {},
        output: {},
        construction: {CivGPT: 100, Peace: 100, PlanetaryRover: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Dyson_sphere",
    },

    MatrioshkaBrain: {
        name: () => t(L.MatrioshkaBrain),
        desc: () => t(L.MatrioshkaBrainDescV2),
        input: {},
        output: {},
        construction: {CivOasis: 100, Peace: 100, CivGPT: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Matrioshka_brain",
    },

    LargeHadronCollider: {
        name: () => t(L.LargeHadronCollider),
        desc: () => t(L.LargeHadronColliderDescV2),
        input: {},
        output: {},
        construction: {Supercomputer: 100, CivTok: 100, HedgeFund: 100},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        wikipedia: "Large_Hadron_Collider",
    },

    BigBen: {
        name: () => t(L.BigBen),
        desc: () => t(L.BigBenDesc),
        input: {},
        output: {},
        max: 1,
        special: BuildingSpecial.WorldWonder,
        construction: {Politics: 300},
        wikipedia: "Big_Ben",
    },

    // ArcDeTriomphe: {
    //    name: () => t(L.ArcDeTriomphe),
    //    desc: () => t(L.ArcDeTriompheDesc),
    //    input: {},
    //    output: {},
    //    construction: { Culture: 100, Brick: 100, Marble: 100 },
    //    max: 1,
    //    special: BuildingSpecial.WorldWonder,
    //    wikipedia: "Arc_de_Triomphe",
    // },
    // #endregion /////////////////////////////////////////////////////////////////////////////////////////////

    // Winery: {
    //    name: () => t(L.Winery),
    //    input: { Grape: 1, Water: 1 },
    //    output: { Wine: 1 },
    //    construction: { Stone: 1, Marble: 1 },
    // },

    // Borobudur: {
    //    name: () => t(L.Borobudur),
    //    desc: () => t(L.BorobudurDesc),
    //    input: {},
    //    output: {},
    //    max: 1,
    //    wikipedia: "Borobudur",
    // },

    // ItsukushimaShrine: {
    //    name: () => t(L.ItsukushimaShrine),
    //    desc: () => t(L.ItsukushimaShrineDesc),
    //    input: {},
    //    output: {},
    //    max: 1,
    //    wikipedia: "Itsukushima_Shrine",
    // },

    // Moai: {
    //    name: () => t(L.Moai),
    //    desc: () => t(L.MoaiDesc),
    //    input: {},
    //    output: {},
    //    max: 1,
    //    wikipedia: "Moai",
    // },

    // BranCastle: {
    //    name: () => t(L.BranCastle),
    //    desc: () => t(L.BranCastleDesc),
    //    input: {},
    //    output: {},
    //    max: 1,
    //    wikipedia: "Bran_Castle",
    // },

    // ChoghaZanbil: {
    //    name: () => t(L.ChoghaZanbil),
    //    desc: () => t(L.ChoghaZanbilDesc),
    //    input: {},
    //    output: {},
    //    max: 1,
    //    wikipedia: "Chogha_Zanbil",
    // },

    // SydneyOperaHouse: {
    //    name: () => t(L.SydneyOperaHouse),
    //    desc: () => t(L.SydneyOperaHouseDesc),
    //    input: {},
    //    output: {},
    //    max: 1,
    //    wikipedia: "Sydney_Opera_House",
    // },

    // FishPond: {
    //    name: () => t(L.FishPond),
    //    input: {},
    //    deposit: { Water: true },
    //    output: { Fish: 1 },
    //    construction: { Brick: 1 },
    // },

    // OlivePlantation: {
    //    name: () => t(L.OlivePlantation),
    //    input: {},
    //    output: { Olive: 1 },
    //    construction: { Wood: 1 },
    // },

    // Vineyard: {
    //    name: () => t(L.Vineyard),
    //    input: {},
    //    output: { Grape: 1 },
    //    construction: { Wood: 1 },
    // },

    // OilPress: {
    //    name: () => t(L.OilPress),
    //    input: { Olive: 2 },
    //    output: { OliveOil: 1 },
    //    construction: { Brick: 1 },
    // },
}